<?xml version="1.0" encoding="utf-8"?><Database Name="CatalogDatabase" Class="CatalogDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\DB\CatalogDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CatalogDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PathToPhoto" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_Machinery" Member="Machineries" ThisKey="Id" OtherKey="UserAuthor" Type="Machinery" />
      <Association Name="AspNetUser_Document" Member="Documents" ThisKey="Id" OtherKey="UserAuthor" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
      <Association Name="AspNetRole_AccessCatalogCategory" Member="AccessCatalogCategories" ThisKey="Id" OtherKey="RoleID" Type="AccessCatalogCategory" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[__MigrationHistory]" Member="__MigrationHistories">
    <Type Name="__MigrationHistory">
      <Column Name="MigrationId" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContextKey" Type="System.String" DbType="NVarChar(300) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProductVersion" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CatalogCategories" Member="CatalogCategories">
    <Type Name="CatalogCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="CatalogCategory_AccessCatalogCategory" Member="AccessCatalogCategories" ThisKey="Id" OtherKey="CategoryID" Type="AccessCatalogCategory" />
      <Association Name="CatalogCategory_Machinery" Member="Machineries" ThisKey="Id" OtherKey="Category" Type="Machinery" />
      <Association Name="CatalogCategory_MandatSpecificCatalogCategory" Member="MandatSpecificCatalogCategories" ThisKey="Id" OtherKey="CatalogCategoryID" Type="MandatSpecificCatalogCategory" />
    </Type>
  </Table>
  <Table Name="dbo.AccessCatalogCategories" Member="AccessCatalogCategories">
    <Type Name="AccessCatalogCategory">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="R" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="W" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CatalogCategory_AccessCatalogCategory" Member="CatalogCategory" ThisKey="CategoryID" OtherKey="Id" Type="CatalogCategory" IsForeignKey="true" />
      <Association Name="AspNetRole_AccessCatalogCategory" Member="AspNetRole" ThisKey="RoleID" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Machinery" Member="Machineries">
    <Type Name="Machinery">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserAuthor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PathToPhoto" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Machinery_MachineSpecification" Member="MachineSpecifications" ThisKey="Id" OtherKey="MachineID" Type="MachineSpecification" />
      <Association Name="Machinery_MachineTag" Member="MachineTags" ThisKey="Id" OtherKey="MachineID" Type="MachineTag" />
      <Association Name="Machinery_Document" Member="Documents" ThisKey="Id" OtherKey="MachineID" Type="Document" />
      <Association Name="CatalogCategory_Machinery" Member="CatalogCategory" ThisKey="Category" OtherKey="Id" Type="CatalogCategory" IsForeignKey="true" />
      <Association Name="AspNetUser_Machinery" Member="AspNetUser" ThisKey="UserAuthor" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MachineSpecifications" Member="MachineSpecifications">
    <Type Name="MachineSpecification">
      <Column Name="MachineID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SpecificationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Machinery_MachineSpecification" Member="Machinery" ThisKey="MachineID" OtherKey="Id" Type="Machinery" IsForeignKey="true" />
      <Association Name="Specification_MachineSpecification" Member="Specification" ThisKey="SpecificationID" OtherKey="Id" Type="Specification" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MachineTags" Member="MachineTags">
    <Type Name="MachineTag">
      <Column Name="MachineID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Machinery_MachineTag" Member="Machinery" ThisKey="MachineID" OtherKey="Id" Type="Machinery" IsForeignKey="true" />
      <Association Name="Tag_MachineTag" Member="Tag" ThisKey="TagID" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Specifications" Member="Specifications">
    <Type Name="Specification">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Specification_MachineSpecification" Member="MachineSpecifications" ThisKey="Id" OtherKey="SpecificationID" Type="MachineSpecification" />
      <Association Name="Specification_MandatSpecificCatalogCategory" Member="MandatSpecificCatalogCategories" ThisKey="Id" OtherKey="SpecificationID" Type="MandatSpecificCatalogCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Tag_MachineTag" Member="MachineTags" ThisKey="Id" OtherKey="TagID" Type="MachineTag" />
    </Type>
  </Table>
  <Table Name="dbo.MandatSpecificCatalogCategories" Member="MandatSpecificCatalogCategories">
    <Type Name="MandatSpecificCatalogCategory">
      <Column Name="SpecificationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CatalogCategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CatalogCategory_MandatSpecificCatalogCategory" Member="CatalogCategory" ThisKey="CatalogCategoryID" OtherKey="Id" Type="CatalogCategory" IsForeignKey="true" />
      <Association Name="Specification_MandatSpecificCatalogCategory" Member="Specification" ThisKey="SpecificationID" OtherKey="Id" Type="Specification" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserAuthor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PathToFile" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Machinery_Document" Member="Machinery" ThisKey="MachineID" OtherKey="Id" Type="Machinery" IsForeignKey="true" />
      <Association Name="AspNetUser_Document" Member="AspNetUser" ThisKey="UserAuthor" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>